/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rr.authadi.test

import com.rr.authadi.ServiceRunner
import kotlin.test.Test
import kotlin.test.assertNotNull

class ServiceRunnerTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = ServiceRunner()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
